### ISSUE TITLE
iOS share sheet

### ISSUE THREAD

**Issue by bcomnes** [hifiwi-fi/breadcrum.net#116]
Find a solution to create a share sheet item.  Probably will require a native solution but maybe there is some kind of web solution I can use.

**Comment by voxpelli** [comment]
Making something on top of Shortcuts is probably the easiest

**Comment by bcomnes** [comment]
I looked at it for 10 minutes this morning and couldn't figure it out. Will have to do more research.

**Comment by voxpelli** [comment]
Here’s a simple one I’m using to subscribe to feeds in Feedbin: https://www.icloud.com/shortcuts/c5ffdb733626488e9ec33e268417c3c6

It simply opens the Feedbin page prefilled with the page URL.

One might be able to go further and do a full API submit, though it can get crazy:

* https://youtu.be/U7hUR7flTAY
* https://youtube.com/shorts/CBPmSpD2jN4?feature=share

**Comment by bcomnes** [comment]
Done in https://breadcrum.net/docs/bookmarklets/##Apple%20Shortcut
