### ISSUE TITLE
Scale db to two processes

### ISSUE THREAD

**Issue by bcomnes** [hifiwi-fi/breadcrum.net#315]
Do a redundant postgres arrangement as recommended by fly.

**Comment by voxpelli** [comment]
Are you sure you need this? Having backups that you can restore is good enough for the current level of service of it, no?

**Comment by bcomnes** [comment]
Maybe though I presume it's easier to set up now rather than later. Maybe it's the same.

**Comment by bcomnes** [comment]
Done.
